volumes:
  mysql_data:

#
# docker-compose up -d
#
services:

  #
  # docker-compose build www
  #
  www:
    image: abenevaut/yaf-cms:local
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPOSER_HASH: dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6
    ports:
      - 8080:8080
    volumes:
      - ${USERPROFILE:-~}/.composer:/root/.composer
      - .:/var/task
