<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= $content ?></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
</head>
<body class="flex column min-height-full">

    <header class="flex wrap-no gap_xs ma-t_m">
        <nav>
            <div>
                <a href="/">YAF-CMS</a>
            </div>
        </nav>
    </header>

    <main>
        <div class="grid">
            <div>YAF-CMS, lightweight PHP framework</div>
        </div>
        <div class="grid">
            <div>based on robust packages</div>
        </div>
    </main>

    <footer>
        <nav>
            <div>
                <b>YAF-CMS</b>
            </div>
            <div>
                <a href="https://github.com/abenevaut/yafarel">GitHub ›</a>
            </div>
        </nav>
    </footer>

</body>
</html>
<!-- You have reached the end of the internet  -->
