<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?= $layoutData['title'] ?></title>
    <meta name="description" content="A layout example that shows off a responsive product landing page.">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css" integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- https://github.com/pure-css/pure/tree/main/site/static/layouts/marketing -->
    <style>
        * {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        body {
            line-height: 1.7em;
            color: #7f8c8d;
            font-size: 13px;
        }
        h1, h2, h3, h4, h5, h6, label {
            color: #34495e;
        }
        .pure-form label {
            margin: 1em 0 0;
            font-weight: bold;
            font-size: 100%;
        }
        .pure-form input[type] {
            border: 2px solid #ddd;
            box-shadow: none;
            font-size: 100%;
            width: 100%;
            margin-bottom: 1em;
        }
        .home-menu {
            padding: 0.5em;
            text-align: left;
            box-shadow: 0 1px 1px rgba(0,0,0, 0.10);
        }
        .home-menu {
            background: #2d3e50;
        }
        .pure-menu.pure-menu-fixed {
            border-bottom: none;
            z-index: 4;
        }
        .home-menu .pure-menu-heading {
            color: white;
            font-weight: 400;
            font-size: 120%;
        }
        .home-menu .pure-menu-selected a {
            color: white;
        }
        .home-menu a {
            color: #6FBEF3;
        }
        .home-menu ul {
            float: right;
        }
        .home-menu li a:hover,
        .home-menu li a:focus {
            background: none;
            border: none;
            color: #AECFE5;
        }
        .splash-container {
            background: #1f8dd6;
            z-index: 1;
            overflow: hidden;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            position: fixed !important;
        }
        .splash {
            width: 100%;
            height: 100%;
            margin: auto;
            position: absolute;
            top: 100px; left: 0; bottom: 0; right: 0;
            text-align: center;
            text-transform: uppercase;
        }
        .splash-head {
            font-size: 20px;
            font-weight: bold;
            color: white;
            border: 3px solid white;
            padding: 1em 1.6em;
            font-weight: 100;
            border-radius: 5px;
            line-height: 1em;
        }
        .content {
            padding: 1em 1em 3em;
        }

        @media (min-width: 48em) {
            body {
                font-size: 16px;
            }
            .splash {
                width: 50%;
                height: 50%;
            }
            .splash-head {
                font-size: 250%;
            }
            .l-box-lrg {
                border: none;
            }
        }
        @media (min-width: 78em) {
            .splash-head {
                font-size: 300%;
            }
        }
    </style>
</head>
<body>

    <div class="header">
        <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
            <a class="pure-menu-heading" href="">YAF CMS</a>

            <ul class="pure-menu-list">
                <li class="pure-menu-item pure-menu-selected"><a href="/" class="pure-menu-link">Home</a></li>
                <li class="pure-menu-item"><a href="https://github.com/abenevaut/yaf-cms" class="pure-menu-link">Github</a></li>
            </ul>
        </div>
    </div>

    <?= $layoutData['content'] ?>

</body>
</html>
<!-- You have reached the end of the internet  -->