name: release-docker

on:
  push:
    tags:
      - docker-*

env:
  php_version: 81

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Get current release tag
        id: branch-name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/docker-}

      - name: Build docker image abenevaut/yafarel
        run: |
          docker login -u ${{ secrets.ABENEVAUT_DOCKER_USERNAME }} -p ${{ secrets.ABENEVAUT_DOCKER_PASSWORD }}
          docker build . --file Dockerfile.yaf --tag abenevaut/yafarel:${{ steps.branch-name.outputs.SOURCE_TAG }}-php${{ env.php_version }} --cache-from abenevaut/yafarel:latest-php${{ env.php_version }}
          docker tag abenevaut/yafarel:${{ steps.branch-name.outputs.SOURCE_TAG }}-php${{ env.php_version }} abenevaut/yafarel:latest-php${{ env.php_version }}
          docker push --all-tags abenevaut/yafarel

      - name: Build docker image abenevaut/yafarel-ci
        run: |
          docker login -u ${{ secrets.ABENEVAUT_DOCKER_USERNAME }} -p ${{ secrets.ABENEVAUT_DOCKER_PASSWORD }}
          docker build . --file Dockerfile.ci --tag abenevaut/yafarel-ci:${{ steps.branch-name.outputs.SOURCE_TAG }}-php${{ env.php_version }} --cache-from abenevaut/yafarel-ci:latest-php${{ env.php_version }}
          docker tag abenevaut/yafarel-ci:${{ steps.branch-name.outputs.SOURCE_TAG }}-php${{ env.php_version }} abenevaut/yafarel-ci:latest-php${{ env.php_version }}
          docker push --all-tags abenevaut/yafarel-ci
