name: release-docker

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile.yaf
      - Dockerfile.ci

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag abenevaut/yaf-framework:tests
#          docker build . --file Dockerfile --tag abenevaut/yaf-framework-ci:tests
          docker login -u ${{ secrets.ABENEVAUT_DOCKER_USERNAME }} -p ${{ secrets.ABENEVAUT_DOCKER_PASSWORD }}
          docker push abenevaut/yaf-framework:0.php81
#          docker push abenevaut/yaf-framework-ci:0.php81
