name: release-docker

on:
  pull_request:
    branches: [ master ]
    paths:
      - Dockerfile.yaf
      - Dockerfile.ci
      - runtime
      - spec
      - .rspec
      - .rubocop.yml
      - Gemfile
      - .Gemfile.lock
  push:
    branches:
      - master
    paths:
      - Dockerfile.yaf
      - Dockerfile.ci

env:
  php_version: 81

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: "Set current date as env variable"
        run: |
          echo "builddate=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        id: version  # this is used on variable path

      - name: Build docker image abenevaut/yaf-framework
        run: |
          docker login -u ${{ secrets.ABENEVAUT_DOCKER_USERNAME }} -p ${{ secrets.ABENEVAUT_DOCKER_PASSWORD }}
          docker pull abenevaut/yaf-framework:latest-php${{ env.php_version }}
          docker build . --file Dockerfile.yaf --tag abenevaut/yaf-framework:${{ steps.version.outputs.builddate }}-php${{ env.php_version }} --cache-from abenevaut/yaf-framework:latest-php${{ env.php_version }}
          docker tag abenevaut/yaf-framework:${{ steps.version.outputs.builddate }}-php${{ env.php_version }} abenevaut/yaf-framework:latest-php${{ env.php_version }}
          docker push --all-tags abenevaut/yaf-framework

      - name: Build docker image abenevaut/yaf-framework-ci
        run: |
          docker login -u ${{ secrets.ABENEVAUT_DOCKER_USERNAME }} -p ${{ secrets.ABENEVAUT_DOCKER_PASSWORD }}
          docker pull abenevaut/yaf-framework-ci:latest-php${{ env.php_version }}
          docker build . --file Dockerfile.yaf --tag abenevaut/yaf-framework-ci:${{ steps.version.outputs.builddate }}-php${{ env.php_version }} --cache-from abenevaut/yaf-framework-ci:latest-php${{ env.php_version }}
          docker tag abenevaut/yaf-framework-ci:${{ steps.version.outputs.builddate }}-php${{ env.php_version }} abenevaut/yaf-framework-ci:latest-php${{ env.php_version }}
          docker push --all-tags abenevaut/yaf-framework-ci
