name: release-docker

on:
  push:
    tags:
      - docker-*

env:
  php_version: 81

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Get current release tag
        id: branch-name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/docker-}

      - name: Build docker image abenevaut/yaf-framework
        run: |
          docker login -u ${{ secrets.ABENEVAUT_DOCKER_USERNAME }} -p ${{ secrets.ABENEVAUT_DOCKER_PASSWORD }}
          docker pull abenevaut/yaf-framework:latest-php${{ env.php_version }}
          docker build . --file Dockerfile.yaf --tag abenevaut/yaf-framework:${{ steps.branch-name.outputs.SOURCE_TAG }}-php${{ env.php_version }} --cache-from abenevaut/yaf-framework:latest-php${{ env.php_version }}
          docker tag abenevaut/yaf-framework:${{ steps.branch-name.outputs.SOURCE_TAG }}-php${{ env.php_version }} abenevaut/yaf-framework:latest-php${{ env.php_version }}
          docker push --all-tags abenevaut/yaf-framework

      - name: Build docker image abenevaut/yaf-framework-ci
        run: |
          docker login -u ${{ secrets.ABENEVAUT_DOCKER_USERNAME }} -p ${{ secrets.ABENEVAUT_DOCKER_PASSWORD }}
          docker pull abenevaut/yaf-framework-ci:latest-php${{ env.php_version }}
          docker build . --file Dockerfile.yaf --tag abenevaut/yaf-framework-ci:${{ steps.branch-name.outputs.SOURCE_TAG }}-php${{ env.php_version }} --cache-from abenevaut/yaf-framework-ci:latest-php${{ env.php_version }}
          docker tag abenevaut/yaf-framework-ci:${{ steps.branch-name.outputs.SOURCE_TAG }}-php${{ env.php_version }} abenevaut/yaf-framework-ci:latest-php${{ env.php_version }}
          docker push --all-tags abenevaut/yaf-framework-ci
