name: test-docker

on:
  push:
    branches: [ php81 ]
    paths:
      - Dockerfile.yaf
      - Dockerfile.ci
      - rootfs
      - tests/spec
      - .rspec
      - .rubocop.yml
      - Gemfile
      - .Gemfile.lock
  pull_request:
    branches: [ php81 ]
    paths:
      - Dockerfile.yaf
      - Dockerfile.ci
      - rootfs
      - tests/spec
      - .rspec
      - .rubocop.yml
      - Gemfile
      - .Gemfile.lock

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - run: docker pull hadolint/hadolint

      - name: lint Dockerfile.yaf
        run: docker run --rm -i hadolint/hadolint < Dockerfile.yaf

#      - name: lint Dockerfile.ci
#        run: docker run --rm -i hadolint/hadolint < Dockerfile.ci

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Run tests
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
          bundle exec rspec tests/spec/dockerfile_yaf_spec.rb
          bundle exec rspec tests/spec/dockerfile_ci_spec.rb
