name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  php_version: 81

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: abenevaut/yafarel-ci:latest-php81
      volumes:
        - ${{ github.workspace }}/vendor:/composer/vendor
    concurrency:
      group: test-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: true
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: |
          cp app.ini.example app.ini
          composer validate --strict
          composer install --optimize-autoloader --no-interaction --prefer-dist
          vendor/bin/phpunit
