name: test-docker

on:
  push:
    branches: [ master ]
    paths:
      - Dockerfile.yaf
      - Dockerfile.ci
      - runtime
      - spec
      - .rspec
      - .rubocop.yml
      - Gemfile
      - .Gemfile.lock
  pull_request:
    branches: [ master ]
    paths:
      - Dockerfile.yaf
      - Dockerfile.ci
      - runtime
      - spec
      - .rspec
      - .rubocop.yml
      - Gemfile
      - .Gemfile.lock

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: lint docker files
        run: |
          docker pull hadolint/hadolint
          docker run --rm -i hadolint/hadolint < Dockerfile.yaf
          docker run --rm -i hadolint/hadolint < Dockerfile.ci
      - name: Build docker images with rspec tag for tests
        run:
          docker pull abenevaut/yaf-framework:latest-php${{ env.php_version }}
          docker build . --file Dockerfile.yaf --tag abenevaut/yaf-framework:rspec --cache-from abenevaut/yaf-framework:latest-php${{ env.php_version }}
          docker pull abenevaut/yaf-framework-ci:latest-php${{ env.php_version }}
          docker build . --file Dockerfile.ci --tag abenevaut/yaf-framework-ci:rspec --cache-from abenevaut/yaf-framework-ci:latest-php${{ env.php_version }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Run tests on docker image with rspec tag
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
          bundle exec rspec
