name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  php_version: 83

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/abenevaut/yaf-cms:latest-php83-testing
      volumes:
        - ${{ github.workspace }}/vendor:/composer/vendor
    concurrency:
      group: test-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: true
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Test
        run: |
          cp app.ini.example app.ini
          composer validate --strict
          composer install --optimize-autoloader --no-interaction --prefer-dist
          XDEBUG_MODE=coverage vendor/bin/phpunit
