name: test-docker

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - Dockerfile.testing
      - rootfs
      - tests/spec
      - .rspec
      - .rubocop.yml
      - Gemfile
      - .Gemfile.lock
  pull_request:
    branches: [ main ]
    paths:
      - Dockerfile
      - Dockerfile.testing
      - rootfs
      - tests/spec
      - .rspec
      - .rubocop.yml
      - Gemfile
      - .Gemfile.lock

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - run: docker pull hadolint/hadolint

      - name: lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile

      - name: lint Dockerfile.testing
        run: docker run --rm -i hadolint/hadolint < Dockerfile.testing

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # docker run -it -v .:/var/task -v /var/run/docker.sock:/var/run/docker.sock:ro -w /var/task ruby:3.2 /bin/sh
      - name: Run tests
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
          bundle exec rspec tests/spec/dockerfile_local_spec.rb
          bundle exec rspec tests/spec/dockerfile_testing_spec.rb
