name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  php_version: 8.1

jobs:

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: test-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: true
#    services:
#      mysql:
#        image: mysql:8.0
#        env:
#          MYSQL_ALLOW_EMPTY_PASSWORD: false
#          MYSQL_ROOT_PASSWORD: password
#          MYSQL_DATABASE: yaf-framework.testing
#        ports:
#          - 3306/tcp
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          extensions: yaf
          coverage: pcov
          tools: composer:v2

      - name: Configure Composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ env.php_version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-node-php_${{ env.php_version }}-

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer -V
          composer validate --strict
          composer install --optimize-autoloader --no-interaction --prefer-dist

      - name: Test
        run: |
          cp app.ini.example app.ini
          vendor/bin/phpunit --coverage-clover=coverage/clover.xml
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          DB_PASSWORD: password

#      - name: Send coverage
#        run: |
#          bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
